### PR TITLE
add color-dependent tpcf test

### PR DESCRIPTION
**Pull request by yymao**
This PR adds the color-dependent tpcf test (as requested in #73). A run of this test on the protoDC2 catalog can be found at:
https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-04-07_24&test=tpcf_Zehavi2011_color

While the code works, there seems to be some issues/bugs with the correlation calculation. However, I still wasn't able to identify the issue. So I'm still submitting this PR and hopefully people can take a look. 

(cc @evevkovacs @vvinuv @aphearin)

### CODE REVIEW

**Comment by yymao** [comment]
@aphearin @evevkovacs I think I understand why the correlation functions look strange in some cases -- I don't think we have enough galaxies for some of these samples given the redshift cuts we applied! In particular, I now print out the galaxy count in each sample and you can see that [these numbers] are not large enough to produce robust measurement. If we want to test low-z clustering maybe we need to do it on snapshots?

**Comment by aphearin** [comment]
What is the redshift range @yymao - these numbers are awfully low?

**Comment by yymao** [comment]
We are using the redshift ranges as in Zehavi 2011. However, due to the small sky area of protoDC2, there's very few galaxies in those low redshift bins (volume too small). So I think we'll have to test this on snapshot catalogs (unless there's other smart suggestions).

**Comment by evevkovacs** [comment]
@yymao @aphearin  But I recall the test results also didn't look good for Buzzard  and that catalogue should not suffer from lack of galaxies. We should run Buzzard through all of the latest versions of these correlation-function tests to see where we stand.

**Comment by yymao** [comment]
@evevkovacs I don't think we've run tpcf on the full Buzzard --- we might have to submit a job for that.

**Comment by evevkovacs** [comment]
I think it would be worth doing. Run all of the available tpcf tests

**Pull request merged**
