### PR TITLE
Add ability to filter catalog before running readiness test

### PR DESCRIPTION
**Pull request by evevkovacs**
> If you are submitting a PR for a validation test (either adding a new one or updating an existing one), please post a link to the DESCQA web interface for the test you are submitting. 
This addition allows a filter to be applied to the catalog data before running the readiness tests. This was useful for testing the new baseDC2_5000 against the old catalog. baseDC2_5000 has a stellar-mass cut applied, which reduces the number of synthetic galaxies. I wanted to apply the same cut to the old baseDC2 catalog to do a comparison. The cosmic variance of the redshift distribution was of particular interest. Here's an [example run for healpixel 9556](https://portal.nersc.gov/cfs/lsst/descqa/v2/?run=2020-05-01_10&test=readiness_baseDC2_sm_cut)

### CODE REVIEW

**Comment by yymao** [comment]
#202 should fix the linter issue.

**Comment by evevkovacs** [comment]
@yymao I wasn't sure how to trigger another run of the checks, so I made a trivial change in the code and pushed to the branch. As you can see the checks failed. But all the complaints from pylint are about other descqa functions, not the one for this PR. Should I attempt to fix those? What about:   descqa.egg-info/__init__.py:1:0: F0010: error while code parsing: Unable to load file descqa.egg-info/__init__.py:
[Errno 2] No such file or directory: 'descqa.egg-info/__init__.py' (parse-error) 
I don't know how to fix this one. There are also complaints about wheel not being installed. I assume that I can ignore those.

**Comment by yymao** [comment]
I just merged #202 and update this branch. The checks are being rerun now.

**Comment by evevkovacs** [comment]
@yymao Ah, you hadn't pushed to master yet. OK, so now everything passed. Could you please re-approve, and then I will merge? Thanks, and sorry for my confusion.  BTW, for future reference, how do I trigger a rerun of the checks without changing the code.

**Comment by yymao** [comment]
@evevkovacs I think if you go to the ["Actions" tab](https://github.com/LSSTDESC/descqa/actions), and then select the failing run, and then click "build (3.7)" from the left sidebar, and then you should see a "Re-run all jobs" button on the very right end. 

image

**Comment by evevkovacs** [comment]
Thanks!

**Pull request merged**
